import { Product } from "@/types";

export const PRODUCTS: Product[] = [
  // 1. The French Flax Linen Sheet Set (Hero / Bestseller)
  {
    id: "prod-1",
    name: "The French Flax Linen Sheet Set",
    slug: "french-flax-linen-sheet-set",
    tagline: "Stone-Washed Normandy Flax • Impossibly Soft from Night One",
    description: "Crafted from 100% long-staple French flax harvested in Normandy. Pre-washed with volcanic stones for signature lived-in drape, breathability, and exceptional temperature regulation. OEKO-TEX Standard 100 certified free from harmful synthetics.",
    category: "bedsheets",
    categoryLabel: "Bedsheets",
    basePrice: 285,
    rating: 4.9,
    reviewCount: 438,
    material: "100% French Flax Linen",
    threadCountOrGsm: "175 GSM",
    origin: "Normandy, France",
    isBestSeller: true,
    availableSizes: ["Full", "Queen", "King", "Cal King"],
    availableColors: [
      { name: "Warm Ivory", hex: "#FAF7F2" },
      { name: "Soft Sand", hex: "#E8DFD0" },
      { name: "Muted Sage", hex: "#C2C9BC" },
      { name: "Dune Mist", hex: "#D6CEBF" },
      { name: "French Charcoal", hex: "#3B3A36" },
    ],
    features: [
      "Woven from slow-harvested 100% Normandy flax",
      "Pumice stone-washed for instant lived-in handfeel",
      "Deep 16\" fitted sheet pocket with 360° high-tensile elastic",
      "Includes 1 fitted sheet, 1 flat sheet, and 2 tailored envelope pillowcases",
      "OEKO-TEX® Standard 100 Certified (Zero formaldehyde & toxic dyes)",
    ],
    dimensions: {
      fitted: "60\" W × 80\" L + 16\" deep pocket (Queen)",
      flat: "96\" W × 108\" L with 4\" double-turned cuff",
      cases: "20\" W × 30\" L with deep 8\" interior envelope closure",
    },
    images: [
      {
        id: "img-1-1",
        productId: "prod-1",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuD4-I1K4vbNsICIYjZwoz76sC8eark0SaLCinQ02L5WbuHtIK9LKjZHfbdct-MVjWJSFfhuGfB7cdqZigy00l7f5qJANIQ7KWF5_og5iivfRMvVDcdTsEP7fPkt5RehCVzYUPKR7JagrOTXZlR3QyYU4L2H5WQSLA0MRUHM4ZB0sniWUsXZGquPIyFldicPjdfkWIyhoGllR5wOP4SOGxscuAPOLf7YSSpnJNZp3kRWAy-JthZi_vhtBQ",
        altText: "French flax linen bedsheet set draped over a low-profile platform bed in morning sunlight",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img-1-2",
        productId: "prod-1",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuD00i2AEdWa1ZmM8iPW5V3ESvAqIR743p80UFxJrvJGUtGwOfyJnQPzh58GYWwQp_NdA3nlXg3Ag2058VsfRBLD29nbcH_e699AbvG54s_2aXkfqydR5dKxSgFsU_DSmMlOM78Z_LwE_gLBiVxnKKAwVDn2MGv-CiDKxoQ-sVy3BWPUIF2QJkyAYLQSvNq-gICYAzeg6KMGe-mxMgNbcYB-VgyL2j1MvuSevA25HFRFemwkmy_jBkj-GQ",
        altText: "Close-up textural view of natural French flax linen bedding with crinkled weave",
        sortOrder: 1,
      },
      {
        id: "img-1-3",
        productId: "prod-1",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCy3FKm8z8HdY1prOMc94xIOhSYz7NHLawmHjW6oZqnQhzDvKgWYI-k1FbXUYQgvjsXE29yd86pCxsCtvqLsWWmQ6cuirfMBxq1IWgdi1d58Zzrq3JjtFTeko2upefCNRHmKiHlbFhR5JYRuuVQq7ZZ-JVnTv5RIa0jVIPSwZaQNK7CXUk1BJpgatEVa7aDNT7I1tE1UveeENAfTy8mezCEeq1c5YsB-wKXG0er7TweutoqB9IghaqbfA",
        altText: "Macro textural weave view of authentic French Normandy flax linen showing organic slubs",
        sortOrder: 2,
      },
      {
        id: "img-1-4",
        productId: "prod-1",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCfLLFw2WH_qNhLQF957rsfjy486tgIpotocui0CBdJZqxW9tY6NJCp_aHOrQoxGqLwpfwrUKaYrhgkLs05fv5vUpWLTfS09YXSIdlOAhdqZr_jL2z48udRzfGN8eHccYOsre0JaYoNT-egUyqtEWi3NYBslPEQDqgj3A68moFkiw3gAzwXPBaEcgdtdpaIbWO5zNBuqhMZ0TfT3PfCaF9Pj0qMS4vMDqqpaDryEJ_bgX8m_E6X1ZxF5w",
        altText: "Stacked warm ivory washed linen sheets folded gently on white oak bench",
        sortOrder: 3,
      },
      {
        id: "img-1-5",
        productId: "prod-1",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuC67jXQbA49MzDskFk-ObAlqr9x12dMpkYxzqIg0gnboTkJYAzdjK_Ke2BV0GqHU2AQTKUMcCJsW-_DB21blkMnO3lj_R376tS1lvcaUPD2NJHannGetaRzNx8ib6aeuMyGC2g-4Z6qcZuk_dLkROJ8L_z7znKVGbCnCZwJspCt2H_v0VWS3rO_517G7ZinqHdLGN7Pk2z54AcSZE0m5YwwC8bmi6GPOYJRknRtfip4dY-ru4M6eypJtg",
        altText: "Detailed close-up of tailored envelope seam on French flax linen pillowcase",
        sortOrder: 4,
      },
    ],
    variants: [
      { id: "v-1-1", productId: "prod-1", size: "Full", colorName: "Warm Ivory", colorHex: "#FAF7F2", price: 265, stock: 12, sku: "FLX-SHT-FUL-IVR" },
      { id: "v-1-2", productId: "prod-1", size: "Queen", colorName: "Warm Ivory", colorHex: "#FAF7F2", price: 285, stock: 24, sku: "FLX-SHT-QEN-IVR" },
      { id: "v-1-3", productId: "prod-1", size: "King", colorName: "Warm Ivory", colorHex: "#FAF7F2", price: 310, stock: 18, sku: "FLX-SHT-KNG-IVR" },
      { id: "v-1-4", productId: "prod-1", size: "Cal King", colorName: "Warm Ivory", colorHex: "#FAF7F2", price: 315, stock: 9, sku: "FLX-SHT-CLK-IVR" },
      { id: "v-1-5", productId: "prod-1", size: "Queen", colorName: "Soft Sand", colorHex: "#E8DFD0", price: 285, stock: 16, sku: "FLX-SHT-QEN-SND" },
      { id: "v-1-6", productId: "prod-1", size: "King", colorName: "Soft Sand", colorHex: "#E8DFD0", price: 310, stock: 11, sku: "FLX-SHT-KNG-SND" },
      { id: "v-1-7", productId: "prod-1", size: "Queen", colorName: "Muted Sage", colorHex: "#C2C9BC", price: 285, stock: 14, sku: "FLX-SHT-QEN-SGE" },
      { id: "v-1-8", productId: "prod-1", size: "Queen", colorName: "French Charcoal", colorHex: "#3B3A36", price: 285, stock: 8, sku: "FLX-SHT-QEN-CHR" },
    ],
  },

  // 2. The Washed Linen Sheet Set (Oatmeal & Alabaster)
  {
    id: "prod-2",
    name: "The Washed Linen Sheet Set",
    slug: "washed-linen-sheet-set",
    tagline: "Volcanic Stone-Washed • Tactile Warmth & Organic Drape",
    description: "Generously washed with volcanic pumice stones for that coveted relaxed architectural drape. Highly breathable for hot sleepers while retaining cozy insulating warmth during cooler months.",
    category: "bedsheets",
    categoryLabel: "Bedsheets",
    basePrice: 285,
    rating: 4.9,
    reviewCount: 428,
    material: "100% French Flax Linen",
    threadCountOrGsm: "180 GSM",
    origin: "Normandy, France",
    isBestSeller: true,
    availableSizes: ["Full", "Queen", "King", "Cal King"],
    availableColors: [
      { name: "Oatmeal", hex: "#E3DAC9" },
      { name: "Warm Alabaster", hex: "#EAE6DF" },
      { name: "Eucalyptus", hex: "#8E9B90" },
    ],
    features: [
      "Airy open-weave flax fibers that breathe naturally",
      "Hypoallergenic and resistant to dust mites",
      "Becomes noticeably softer with every domestic laundry wash",
      "Reinforced corner seams with tailored double stitching",
    ],
    images: [
      {
        id: "img-2-1",
        productId: "prod-2",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDRofftqisNFZnAIUSYleRpMVRqPllNKXpPVacXAK44OvIFuLdg_JofE-s4TefFOv0XqwHfIXu3fTbRpyORmEUf10FMtUz6AQOTCIZDPelG4gnMnKzebeLXDiuBNcXtLWw4g72Ult4i64ZI7H2s0DlKcx5-M61Q_uC0RFj9hlwhH9vkIMgNARCiaVUT21pKMT8fS0fAVjkCmtTGUqqkQasl15UlqJQGriO9-sQPgX1Utcp3icKTgrtlqw",
        altText: "Washed linen sheet set folded and styled with textured wrinkles",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img-2-2",
        productId: "prod-2",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUZzpp8szKlCaNHPJemnC7kx29DdEaV7E3I1TFOfneVOOybqWHexi6-MoM23vQoMPe-EnSSE2tUyGvgGr3ZTPpE86VvolITvNzUwRts0j1NCnviBoNlO5_6V-s6-RXuAB6NH9REQV0N-tMe6dClU48x6HFueH2sf_aGFB8ibRlDUBD9_BgcAkh1KkDa1a4b1KRICZQhiy1Da8CrR9z0C0iGTVN7zluXFgR4S8CVkA8M_avPXvxdVssvw",
        altText: "Editorial flat lay of luxury French flax bedsheets in neutral oatmeal",
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "v-2-1", productId: "prod-2", size: "Queen", colorName: "Oatmeal", colorHex: "#E3DAC9", price: 285, stock: 19, sku: "WSH-SHT-QEN-OAT" },
      { id: "v-2-2", productId: "prod-2", size: "King", colorName: "Oatmeal", colorHex: "#E3DAC9", price: 310, stock: 15, sku: "WSH-SHT-KNG-OAT" },
      { id: "v-2-3", productId: "prod-2", size: "Queen", colorName: "Warm Alabaster", colorHex: "#EAE6DF", price: 285, stock: 22, sku: "WSH-SHT-QEN-ALB" },
    ],
  },

  // 3. Organic Percale Crisp Sheet Set
  {
    id: "prod-3",
    name: "Organic Percale Crisp Sheet Set",
    slug: "organic-percale-crisp-sheet-set",
    tagline: "Cool, Breathable & Matte • Classic Boutique Hotel Weave",
    description: "Woven from 100% long-staple certified organic cotton. Features a traditional 1-over-1 percale weave that delivers an extraordinarily crisp, hotel-bed crunch that stays refreshingly cool all night.",
    category: "bedsheets",
    categoryLabel: "Bedsheets",
    basePrice: 220,
    rating: 4.8,
    reviewCount: 312,
    material: "100% GOTS Organic Cotton",
    threadCountOrGsm: "300 Thread Count",
    origin: "Aegean Coast, Turkey",
    isNewArrival: true,
    availableSizes: ["Twin", "Full", "Queen", "King"],
    availableColors: [
      { name: "Cloud White", hex: "#FFFFFF" },
      { name: "Soft Sky", hex: "#D3DCDD" },
      { name: "Oat", hex: "#E7DFCE" },
    ],
    images: [
      {
        id: "img-3-1",
        productId: "prod-3",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCNHfLXU2kXULSF8fP_zeB6Ei1a_IUr3YTy5x3rRhW0Jl0a6gnJ4kQEYbFuRe7E3LpmKnfLvcuiFIa36kvj7VumZSDz3S5CDXPy_Ym-utttCXg0D-XNiZYY4Ec_wl-luavEHTX0XgnWeJhO4l5AC5eo0J8EMynMk0kODgkoxVg48uJIDYaCRWl_7mQqj23ssYDZs0Nm24fJ4SQDVJUqYhsn46xQOMNb3ezPuc-k80wgg85_P90gzyoDOQ",
        altText: "Crisp white percale sheet set styled under soft ambient daylight",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-3-1", productId: "prod-3", size: "Twin", colorName: "Cloud White", colorHex: "#FFFFFF", price: 190, stock: 10, sku: "PRC-SHT-TWN-WHT" },
      { id: "v-3-2", productId: "prod-3", size: "Queen", colorName: "Cloud White", colorHex: "#FFFFFF", price: 220, stock: 25, sku: "PRC-SHT-QEN-WHT" },
      { id: "v-3-3", productId: "prod-3", size: "King", colorName: "Cloud White", colorHex: "#FFFFFF", price: 245, stock: 18, sku: "PRC-SHT-KNG-WHT" },
    ],
  },

  // 4. Lustrous Sateen Luxe Bedding Set
  {
    id: "prod-4",
    name: "Lustrous Sateen Luxe Bedding Set",
    slug: "lustrous-sateen-luxe-bedding-set",
    tagline: "480 Thread Count • Silky Luster & Velvet-Soft Touch",
    description: "Crafted with ultra-long staple Egyptian cotton spun into fine yarns. The 4-over-1 satin weave produces a subtle champagne luster and an opulent, silky hand that drapes sumptuously over the body.",
    category: "bedsheets",
    categoryLabel: "Bedsheets",
    basePrice: 260,
    rating: 4.9,
    reviewCount: 284,
    material: "100% Giza Egyptian Cotton",
    threadCountOrGsm: "480 Thread Count",
    origin: "Nile Delta, Egypt",
    availableSizes: ["Queen", "King", "Cal King"],
    availableColors: [
      { name: "Champagne Gold", hex: "#DFCFB2" },
      { name: "Pearl Ivory", hex: "#FAF7F0" },
      { name: "Midnight Charcoal", hex: "#24262E" },
    ],
    images: [
      {
        id: "img-4-1",
        productId: "prod-4",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuB56FdgLfRgPf-03KQgSqXwl5YUKPVl3lPEujl1fb9OHEV_3qW7Xhdm-WyQEW2cQu9OSNI5iHh61EpAfsYABPnoDWv8tKMfy3uymtWN0QpYuX2tuXClF9HZsF-MGFIv2jYIVsWdB0NSoc1dCcgsv-vVh-E9moBuTxL31cSy3krMOWEsIAksT1si3e5mm6JN8lS_seQf431lHknzWEJBYMDNRWqFh9CoTSIet_XvMI7Sx8U211Iw7yZDjA",
        altText: "Lustrous sateen sheet set folded gracefully with champagne sheen",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-4-1", productId: "prod-4", size: "Queen", colorName: "Champagne Gold", colorHex: "#DFCFB2", price: 260, stock: 15, sku: "SAT-SHT-QEN-GLD" },
      { id: "v-4-2", productId: "prod-4", size: "King", colorName: "Champagne Gold", colorHex: "#DFCFB2", price: 290, stock: 12, sku: "SAT-SHT-KNG-GLD" },
      { id: "v-4-3", productId: "prod-4", size: "Queen", colorName: "Pearl Ivory", colorHex: "#FAF7F0", price: 260, stock: 20, sku: "SAT-SHT-QEN-IVR" },
    ],
  },

  // 5. Heirloom Belgian Flax Fitted Sheet
  {
    id: "prod-5",
    name: "Heirloom Belgian Flax Fitted Sheet",
    slug: "heirloom-belgian-flax-fitted-sheet",
    tagline: "Single-Farm Belgian Linen • 360° Grip Pocket",
    description: "For discerning sleepers who only need the foundational layer. Tailored from single-farm Belgian flax with 16-inch deep pockets and full-perimeter elastic that never pops off your mattress.",
    category: "bedsheets",
    categoryLabel: "Bedsheets",
    basePrice: 160,
    rating: 4.7,
    reviewCount: 165,
    material: "100% Belgian Flax",
    threadCountOrGsm: "185 GSM",
    origin: "Flanders, Belgium",
    availableSizes: ["Full", "Queen", "King"],
    availableColors: [
      { name: "Natural Ecru", hex: "#DDD5C4" },
      { name: "Bleached White", hex: "#FBFBF9" },
      { name: "Terracotta Dust", hex: "#C69986" },
    ],
    images: [
      {
        id: "img-5-1",
        productId: "prod-5",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDDwM-a6dVO0Rwb1fboVDbOEQFUo0xW9X8yHCWmkPVNEkCRadURI4J7_2YHMV43ATSz1SlTXSpxBUEG4gqatSd4wZ1qFQbZ8U0_tzfFxrWCm_Q3fkMcoY126H4AZIPuc_NOPJZM1Wcys6eeFJp1uQSU8eKq8yUR1Y_qgh5-n_VvEtbAmZyT2w0XVbb05uH6ssmzGYG1irCGIgXzbENi6oJrBUMEl_Pv2BLGxJWNrgJFNwstNrd9HDWZxQ",
        altText: "Fitted flax sheet stacked on a natural cedar surface",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-5-1", productId: "prod-5", size: "Queen", colorName: "Natural Ecru", colorHex: "#DDD5C4", price: 160, stock: 14, sku: "BLG-FIT-QEN-ECR" },
      { id: "v-5-2", productId: "prod-5", size: "King", colorName: "Natural Ecru", colorHex: "#DDD5C4", price: 180, stock: 11, sku: "BLG-FIT-KNG-ECR" },
    ],
  },

  // 6. Cloud Goose Down Duvet Insert
  {
    id: "prod-6",
    name: "Cloud Goose Down Duvet Insert",
    slug: "cloud-goose-down-duvet-insert",
    tagline: "750 Fill Power • Ethical RDS European Goose Down",
    description: "Experience the sensation of sleeping beneath a warm, weightless cloud. Filled with 750 fill-power European white goose down encased in a silent 400-thread count German batiste cotton shell. Baffle-box construction keeps down evenly distributed with zero cold spots.",
    category: "duvets",
    categoryLabel: "Duvets",
    basePrice: 340,
    rating: 5.0,
    reviewCount: 215,
    material: "750 FP White Goose Down & Cotton Batiste",
    threadCountOrGsm: "750 Fill Power",
    origin: "Bavaria, Germany",
    isBestSeller: true,
    availableSizes: ["Twin", "Full / Queen", "King / Cal King"],
    availableColors: [
      { name: "Pristine White", hex: "#FFFFFF" },
      { name: "Antique Ivory", hex: "#FAF5EE" },
    ],
    features: [
      "Responsible Down Standard (RDS) certified ethical down",
      "True 3D baffle-box construction with interior walls",
      "Down-proof double-stitched perimeter with silk piping",
      "Eight corner and side loops to secure duvet ties firmly",
    ],
    images: [
      {
        id: "img-6-1",
        productId: "prod-6",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDiLMU9kFaUz1KJVZYxlqcdVVgrYrcr0LTQtSVR2DGIgnRmWMfYpQrzHABD9WkR_lHMnkQ1W8jrO0PBurY1hDPcmBeFsCo-WEGFg6L19JTAlpqrQNsBgXBSF_UopJpM2FTYSOfLGaY2tq0kvRXgN_Lb7mtF-6QQ3XgWMJIp1pwcaEInGoCAVYHprnIJm3vDVSjipgnetecfX-UErZi9HxOCZubt-PWeghCP4qtPN9SlLSqvkVQNXq_I3w",
        altText: "Cloud goose down duvet insert billowing with airy loft and baffle stitching",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img-6-2",
        productId: "prod-6",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuC0NXP2hbNChx7L7wjaFUnEwbnyhrPP6KcctVdNfN0Ug5QGnTtHZCNsGLpHzULv5Y3mvP0BgIyY91s4Zp4WQn-0mqbOQoXzOEY8hFJdg6Wy3YZi4IVQB62biqR80-2RO46SvVTboTusbVpOO5k8jQEVUUP6LoD7T8V4tYbbCgR9NIR7jETkFO4S9fwiVzZS3u-N3VQKNOSq0YijRII7ha-xAbaCNTg8oc1OdNW0CYU3BP4MjWGBzLuvKQ",
        altText: "Goose down white comforter in airy soft light, fluffy lofty corners",
        sortOrder: 1,
      },
      {
        id: "img-6-3",
        productId: "prod-6",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCGvbMEQI8kk6IWWJQfjvfQccztUVCLoIiPzYqslpMSlvRCAeiMq4AxHTY94Kbss9LriH3okqIjLS3vG0iNERd8N0vdVsUoyf7Uo8Kl_tTTFvKVur1tfD3mW2SHdrnr_deuPkA4ZgBTexcG6lyMIcXRRhCsldKnD2ZgJ4rc4Hui1uLNnB4P4McQgdY4c6CQN6-52-apz-BucRu_Y6gm4QV0RnF09UK1gDS1UqPsxhuGwOXR7NTJQFxOmg",
        altText: "Sumptuous cloud-like down duvet folded with majestic loft on unmade bed",
        sortOrder: 2,
      },
    ],
    variants: [
      { id: "v-6-1", productId: "prod-6", size: "Twin", colorName: "Pristine White", colorHex: "#FFFFFF", price: 295, stock: 8, sku: "DWN-DVT-TWN-WHT" },
      { id: "v-6-2", productId: "prod-6", size: "Full / Queen", colorName: "Pristine White", colorHex: "#FFFFFF", price: 340, stock: 20, sku: "DWN-DVT-QEN-WHT" },
      { id: "v-6-3", productId: "prod-6", size: "King / Cal King", colorName: "Pristine White", colorHex: "#FFFFFF", price: 390, stock: 15, sku: "DWN-DVT-KNG-WHT" },
    ],
  },

  // 7. Heirloom Washed Flax Linen Duvet Cover
  {
    id: "prod-7",
    name: "Heirloom Linen Duvet Cover",
    slug: "heirloom-linen-duvet-cover",
    tagline: "Pure Stone Wash • Genuine Horn Buttons & Corner Ties",
    description: "An editorial centerpiece for your rest suite. Spun from Normandy flax, this cover showcases raw organic slub and subtle wrinkles with an understated drape. Hand-stitched with hidden genuine carved horn buttons.",
    category: "duvets",
    categoryLabel: "Duvets",
    basePrice: 220,
    rating: 4.8,
    reviewCount: 189,
    material: "100% French Flax Linen",
    threadCountOrGsm: "180 GSM",
    origin: "Normandy, France",
    isBestSeller: true,
    availableSizes: ["Full / Queen", "King / Cal King"],
    availableColors: [
      { name: "Muted Sage", hex: "#8A9A86" },
      { name: "Natural Flax", hex: "#E5DCC5" },
      { name: "Roasted Chestnut", hex: "#C2A68C" },
    ],
    images: [
      {
        id: "img-7-1",
        productId: "prod-7",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCtOoYRRk0vGHuHkhoXB0ih8gsU0xTM_GGMq5APfzivgWXTvPdiG1uI5jfW5mWymwl1GqLYK1sXDsPR60PueZgV_M9jJ6mR4_ORPyDSiIL6iowMgRPg0-4jAEit5AXiKX7v-AEly6B792PSm3XJMHU-6RS572no-rMjGSSppdgxpLhDfgv4UU7c6EJ6R15wlZW6Qn1QOO6xcHPjvGne-45X8aJ-DoUpGwVFICvJVHXa8qcD5tp2I1-uMg",
        altText: "Heirloom linen duvet cover in muted sage resting on an unmade bed",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img-7-2",
        productId: "prod-7",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDiBCnikRLwnd_4Wsq2BV_wVpZaf2My8kvlRPBh3KSFqnjtzRILf4fjs0dPkKD450bxrZH7e861saDA3s6fi430jIcrvFomHmJ1oJU4UYdCmvwbz_FqXd6HYLM4L31NphUK7SlVEgJpOYsVajd7SbfUezj8omF6M9yskA3anvoBdPz7uH_qwNTjuJ2iZVgdlf5XF5jHKDFyRtQD5j2GsNoxvU_yFqfHBI1ldpcLIHZXhmgDsax5tSQKwA",
        altText: "European bedroom showing linen duvet cover in sage and sand",
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "v-7-1", productId: "prod-7", size: "Full / Queen", colorName: "Muted Sage", colorHex: "#8A9A86", price: 220, stock: 15, sku: "HLM-DVT-QEN-SGE" },
      { id: "v-7-2", productId: "prod-7", size: "King / Cal King", colorName: "Muted Sage", colorHex: "#8A9A86", price: 250, stock: 12, sku: "HLM-DVT-KNG-SGE" },
      { id: "v-7-3", productId: "prod-7", size: "Full / Queen", colorName: "Natural Flax", colorHex: "#E5DCC5", price: 220, stock: 18, sku: "HLM-DVT-QEN-FLX" },
    ],
  },

  // 8. Lightweight Summer Down-Alternative Duvet
  {
    id: "prod-8",
    name: "Lightweight Summer Down-Alternative Duvet",
    slug: "lightweight-summer-down-alternative-duvet",
    tagline: "Micro-Cluster Cloudfiber • Tailored for Warm Sleepers",
    description: "Engineered specifically for summer warmth and humid climates. Packed with hypoallergenic micro-cluster recycled fibers that mimic down fluffiness without trapping excess heat.",
    category: "duvets",
    categoryLabel: "Duvets",
    basePrice: 210,
    rating: 4.7,
    reviewCount: 142,
    material: "Hypoallergenic Cloudfiber & Organic Cotton",
    threadCountOrGsm: "300 GSM",
    origin: "Porto, Portugal",
    availableSizes: ["Full / Queen", "King / Cal King"],
    availableColors: [
      { name: "Crisp Frost", hex: "#F8F9FA" },
      { name: "Dune Warmth", hex: "#EFECE5" },
    ],
    images: [
      {
        id: "img-8-1",
        productId: "prod-8",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQQnW8y3AqJ-LqQ0sToEc-wbBDMGHxZYaSGiIjZ3CqJ3uNUco64p43SZOK5hwdjgz5MGakLFBG3gbErhtmIq-glimwFqafBlxKHMHKNMkUFzgxhzSMZvLISC7NMayG9sjCMMChemnuSnzanw96aZppLtOKTnCOSuEpxALjmUcOuKcA1gL2Bwq0rEb1QPNFxp4B6YFsS6qcOGJHAQbcuqB6MJeiJ1MjD9lY6T2q7TPB3V9-N1iMBUGkUQ",
        altText: "Lightweight summer duvet insert folded on warm wood",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-8-1", productId: "prod-8", size: "Full / Queen", colorName: "Crisp Frost", colorHex: "#F8F9FA", price: 210, stock: 17, sku: "ALT-DVT-QEN-FST" },
      { id: "v-8-2", productId: "prod-8", size: "King / Cal King", colorName: "Crisp Frost", colorHex: "#F8F9FA", price: 235, stock: 14, sku: "ALT-DVT-KNG-FST" },
    ],
  },

  // 9. Pure Silk & French Linen Pillow Pair
  {
    id: "prod-9",
    name: "Pure Silk & French Linen Pillow Pair",
    slug: "pure-silk-french-linen-pillow-pair",
    tagline: "Set of 2 • 22-Momme Mulberry Silk Front & Linen Reverse",
    description: "The ultimate dual-sided sanctuary pillowcase. The front side features smooth 22-momme Mulberry silk to eliminate skin friction and hair tangles; the reverse offers breathable stone-washed French linen for effortless styling.",
    category: "pillows",
    categoryLabel: "Pillows & Covers",
    basePrice: 110,
    rating: 4.9,
    reviewCount: 310,
    material: "Mulberry Silk & French Linen",
    threadCountOrGsm: "22 Momme Silk",
    origin: "Lyon, France",
    isBestSeller: true,
    availableSizes: ["Standard Pair", "King"],
    availableColors: [
      { name: "Soft Sand", hex: "#E5D7C3" },
      { name: "Warm Alabaster", hex: "#F3EDE3" },
      { name: "Noir", hex: "#2C2B29" },
    ],
    images: [
      {
        id: "img-9-1",
        productId: "prod-9",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDvtcld0PtSySoA5T975dGbdmkccRCX4gsE-3zssSMTt517F9m7bmE4yztXKFWy1qrD_D1hlTlOFLtISZBX9g6H1ngTfSwXX809tbglnHp4X6vtwfv76qxGnx6Vjtb4mYSxcsmLQwa8PHWE_swHz4Jfq9LucxbgZz9BgvFygnFWzYd3WLri45V2nqs9OYQ7da1586J6LGnkPv9-tgikYc1ukPXXSPV3GmJ1U-1JWREIA4mCRmZqxyHMrw",
        altText: "Pair of silk and linen pillowcases stacked on warm light oak",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-9-1", productId: "prod-9", size: "Standard Pair", colorName: "Soft Sand", colorHex: "#E5D7C3", price: 110, stock: 22, sku: "SLK-PLW-STD-SND" },
      { id: "v-9-2", productId: "prod-9", size: "King", colorName: "Soft Sand", colorHex: "#E5D7C3", price: 130, stock: 14, sku: "SLK-PLW-KNG-SND" },
      { id: "v-9-3", productId: "prod-9", size: "Standard Pair", colorName: "Warm Alabaster", colorHex: "#F3EDE3", price: 110, stock: 18, sku: "SLK-PLW-STD-ALB" },
    ],
  },

  // 10. French Flax Envelope Linen Pillow Shams (Set of 2)
  {
    id: "prod-10",
    name: "Linen Pillow Shams (Set of 2)",
    slug: "linen-pillow-shams-set-of-2",
    tagline: "Enzyme-Washed Normandy Flax • Deep Envelope Pocket",
    description: "Woven from certified European flax, softened with eco-friendly enzyme stone washing. Features an extra deep 8-inch envelope closure so inserts never poke out, maintaining clean architectural lines.",
    category: "pillows",
    categoryLabel: "Pillows & Covers",
    basePrice: 75,
    rating: 4.8,
    reviewCount: 224,
    material: "100% French Flax Linen",
    threadCountOrGsm: "175 GSM",
    origin: "Normandy, France",
    availableSizes: ["Standard Pair", "King"],
    availableColors: [
      { name: "Muted Sage", hex: "#A2AFA2" },
      { name: "Warm Ivory", hex: "#FAF7F2" },
      { name: "Ochre Sand", hex: "#C8B28E" },
    ],
    images: [
      {
        id: "img-10-1",
        productId: "prod-10",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuAZln3uLX8fzZHDzCdaDgClEvINVhmgMFiG4LsS37402s-SGkXCoE-TIQUWYQ1VX43haCPKu1WNH7BQaD8dnuGl_BXE7OZhLfJ8XcDReVMe9ij43mIRCzskGIHasidrAkhdA9-DJbD0cUNCDiX3kmjrd5ayu3p-M_XEE7KUfQHaP4S7q3kc4IDU28mLbYpUATW3foxTcK2jNND0uSjpwPbtrqE39A80lzluICl4QyPAiAmbRiBPNq_Bjg",
        altText: "Muted sage pure linen pillow shams leaning against ivory wall",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img-10-2",
        productId: "prod-10",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDWZ_RNbIrcC5Spk8mMfc-R3cFjickkzfEcZOjKl_LbCtVYyfbk7pNDZLVlMS4E89O4qB2sqvWxi-4Sit3QBw5FrchwSGD5DoHx_JNumvuylsvpMnwQUrEN8nQTMcM5wr-muGgF4MAvNA9OoF0aASW-JdfsiYot4sQUUBvKScK8ve2Ug9gFJGMOJqwx6MW3OSJ6uuI1tKSzsZJWYtYxZ1dmuSfAxrrMiJAwvMrBSNFsE2DLRac-09wqQA",
        altText: "Two muted sage pillow cases folded neatly in morning shadows",
        sortOrder: 1,
      },
    ],
    variants: [
      { id: "v-10-1", productId: "prod-10", size: "Standard Pair", colorName: "Muted Sage", colorHex: "#A2AFA2", price: 75, stock: 30, sku: "SHM-PLW-STD-SGE" },
      { id: "v-10-2", productId: "prod-10", size: "King", colorName: "Muted Sage", colorHex: "#A2AFA2", price: 90, stock: 15, sku: "SHM-PLW-KNG-SGE" },
      { id: "v-10-3", productId: "prod-10", size: "Standard Pair", colorName: "Warm Ivory", colorHex: "#FAF7F2", price: 75, stock: 25, sku: "SHM-PLW-STD-IVR" },
    ],
  },

  // 11. Cloud-Loft European Goose Down Pillow
  {
    id: "prod-11",
    name: "Cloud-Loft Goose Down Pillow",
    slug: "cloud-loft-goose-down-pillow",
    tagline: "Dual-Chamber Support • Hypoallergenic Bavarian Down",
    description: "Constructed with an ingenious dual-chamber core: dense small feather center for firm cervical support, surrounded by an outer layer of fluffy 750 fill-power goose down for pure buttery loft.",
    category: "pillows",
    categoryLabel: "Pillows & Covers",
    basePrice: 145,
    rating: 4.9,
    reviewCount: 198,
    material: "750 FP White Goose Down & Cotton Cambric",
    threadCountOrGsm: "750 Fill Power",
    origin: "Bavaria, Germany",
    availableSizes: ["Standard", "King"],
    availableColors: [
      { name: "Cambric White", hex: "#FFFFFF" },
    ],
    images: [
      {
        id: "img-11-1",
        productId: "prod-11",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5mg_88uP4_dY0StskHnUAypeSbRoucIm9WT-4HR0oAhnQmLZpvQryGp9dRkRHXbywiF4rdugLcuMoRPigGYCT36DBSF4ZqUkql1Fvbv4FsJR7Z-jb_ZTKaPbn0S4wcKo0yT-u5NMEYIs4dhebchIyjiGTZhd7fCuNLNWfKcX7zNv15mR39syvFaPaBGXjvgohAlrO-ORZS36KvAyWx90TvMz_SjFMWmkOvTp5qjbh_7YVesL5Hn00kw",
        altText: "Plush cloud-loft down pillow resting in linen sham",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-11-1", productId: "prod-11", size: "Standard", colorName: "Cambric White", colorHex: "#FFFFFF", price: 145, stock: 24, sku: "CLD-PLW-STD-WHT" },
      { id: "v-11-2", productId: "prod-11", size: "King", colorName: "Cambric White", colorHex: "#FFFFFF", price: 175, stock: 16, sku: "CLD-PLW-KNG-WHT" },
    ],
  },

  // 12. Ergonomic Memory Latex Neck Contour Pillow
  {
    id: "prod-12",
    name: "Ergonomic Memory Latex Contour Pillow",
    slug: "ergonomic-memory-latex-contour-pillow",
    tagline: "Natural Talalay Latex Core • Orthopedic Align & Cool",
    description: "Breathable open-cell natural Talalay latex molded to cradle the cervical spine. Keeps side and back sleepers neutrally aligned with instant pressure relief and superior thermal airflow.",
    category: "pillows",
    categoryLabel: "Pillows & Covers",
    basePrice: 120,
    rating: 4.8,
    reviewCount: 96,
    material: "100% Talalay Latex & Organic Cotton Cover",
    origin: "Netherlands",
    availableSizes: ["Standard"],
    availableColors: [
      { name: "Natural Ivory", hex: "#F6F3EE" },
    ],
    images: [
      {
        id: "img-12-1",
        productId: "prod-12",
        url: "https://lh3.googleusercontent.com/aida-public/AB6AXuD54RdzxfjYQY5VK2E2YEvG2TQQKrOYkd18sPfUBQ24KHAOELh0da65NV2L7EI765-IpgeW0oAqtBLqXFa-LeJplWH7hH-QmZ44QVt-DlKi_JECUijc_3o4KxvSYyBlvrb2cvSY7kc7Lo0sEWmRPPu4D0dZGKVyK7LazDCPtHogszVTCg44GQp-VYL6PDBQgK1-f3324-KqvsswDBDicK8sWimSOUbQF-Nh2E9R6LNQ5Mwq7dCaPRHHpQ",
        altText: "Ergonomic latex contour pillow with organic cotton knit cover",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: "v-12-1", productId: "prod-12", size: "Standard", colorName: "Natural Ivory", colorHex: "#F6F3EE", price: 120, stock: 18, sku: "LTX-PLW-STD-IVR" },
    ],
  },
];

// Bespoke Cross-Sell Items for Mini Cart and Drawer
export const CROSS_SELL_ITEMS = [
  {
    id: "cs-1",
    name: "Natural Lavender Linen Mist",
    slug: "natural-lavender-linen-mist",
    price: 28,
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCaRnZ1PQF0OEyclGJ_WHgJWj8cg3MUBgmS4Diq9w0pa0HF570lEkiyhnH0n0Nz73gGLDsxqQsgFKgIQQNHn4wzxk1k0hcKLKROLBr001AFYkzAam6bFlkCYavKTjwABr_ThAAHxF38Cp-8WM97GayFtGdlh6FWzyF2raquroccsF9Ce5diGGuhwWpDhUcH8ExrgsZzMzIGhRHXbmL-FxBsUKFIBTohjeaYEHo6Cy15pVCpV1kbK_PKyw",
    tagline: "Organic French Provence Elixir",
    size: "100ml",
    colorName: "Amber Glass",
    colorHex: "#C59B27",
  },
  {
    id: "cs-2",
    name: "Pure Silk Sleep Eye Mask",
    slug: "pure-silk-sleep-eye-mask",
    price: 35,
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuD_q35MAgcDrpiVaZ-YkI2s70wMrVlcBKzmKS0N4rmTjpF9OS2j9ggL0cxz3CgeagnDKPOPoXtfYlkt2ce6ZT2Emq0kMt9iQm5uxT9_HQar4aZOu4mJb0PxCad0mIdFl0mNuhB7P8XYTujbG8d3Hw6EBHZE6uzR_ewrwbm_HzZyRTPmUud0VWlZNIZLa0XBSqh4Kf-qN74DyeuLjlEkTSOyLg_E1-S_UWIszzG4eCBJoq6L0aOerqclJA",
    tagline: "22-Momme Mulberry Silk",
    size: "One Size",
    colorName: "Champagne",
    colorHex: "#DFCFB2",
  },
];
